// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"time"
)

type GooseDbVersion struct {
	ID        int64      `json:"id"`
	VersionID int64      `json:"version_id"`
	IsApplied int64      `json:"is_applied"`
	Tstamp    *time.Time `json:"tstamp"`
}

type ProductDraft struct {
	ID                 string      `json:"id"`
	Status             string      `json:"status"`
	DraftPayload       string      `json:"draft_payload"`
	Url                *string     `json:"url"`
	Source             *string     `json:"source"`
	Title              *string     `json:"title"`
	Description        *string     `json:"description"`
	Currency           *string     `json:"currency"`
	Price              *string     `json:"price"`
	Error              interface{} `json:"error"`
	CreatedBy          interface{} `json:"created_by"`
	CreatedAtMs        int64       `json:"created_at_ms"`
	UpdatedAtMs        int64       `json:"updated_at_ms"`
	PublishedAtMs      interface{} `json:"published_at_ms"`
	PublishedProductID interface{} `json:"published_product_id"`
}
